name: gdata-antivirus
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.WordPress
    restart: always
    ports:
      - 8080:80
    networks:
      static-network:
        ipv4_address: 172.20.128.2
      gdata-antivirus:
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TEST_DB_NAME: wordpress_test
      WORDPRESS_DEBUG: true
    volumes:
      - ./scoped-code/:/var/www/html/wp-content/plugins/gdata-antivirus:ro,cached

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - gdata-antivirus

networks:
  gdata-antivirus:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.5.0/24
