services:
  app:
    image: wordpress:6-php8.3
    restart: always
    ports:
      - 8080:80
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TEST_DB_NAME: wordpress_test
    volumes:
      - .:/var/www/html/wp-content/plugins/wordpress-gdata-antivirus:ro,cached
    networks:
      - wordpress-gdata-antivirus

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress-gdata-antivirus

networks:
  wordpress-gdata-antivirus:
