services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    working_dir: /workspaces/wordpress-gdata-antivirus
    environment: &env
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TEST_DB_NAME: wordpress_test
    volumes:
      - .:/workspaces/wordpress-gdata-antivirus:cached
      - ./local-env:/var/www/html:cached
      - .:/var/www/html/wp-content/plugins/wordpress-gdata-antivirus:ro,cached
    networks:
      - wordpress-gdata-antivirus

  db:
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db:/var/lib/mysql
    networks:
      - wordpress-gdata-antivirus

volumes:
  db:
  wordpress:

networks:
  wordpress-gdata-antivirus:
