# This is the Compose file for command-line services.
# Anything that doesn't need to be run as part of the main `docker-compose up'
# command should reside in here and be invoked by a helper script.
version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    working_dir: /workspaces/wp-vaas
    environment: &env
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TEST_DB_NAME: wordpress_test
    volumes:
      - .:/workspaces/wp-vaas:cached
      - ./local-env:/var/www/html:cached
      - .:/var/www/html/wp-content/plugins/wp-vaas:ro,cached
    networks:
      - wp-vaas

  db:
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db:/var/lib/mysql
      - ./tests/db-wordpress_test.sql:/docker-entrypoint-initdb.d/db-wordpress_test.sql
    networks:
      - wp-vaas

volumes:
  db:
  wordpress:


networks:
  wp-vaas:
